"""
LogClaw Brain - 5W+H Transformation Engine
five_w.py - Converts correlated alerts into investigative narratives

Author  : Rayyan Umair
Date    : 2026-05-09
Purpose : Every alert generated by the correlation engine or Sigma
          engine passes through this module before being stored or
          broadcast. It transforms the structured alert data into a
          5W+H investigative narrative - Who, What, Where, When, Why,
          and How. The How section always contains concrete
          investigation commands and remediation steps that an analyst
          can execute immediately. Works without AI - hardcoded
          templates cover all built-in alert types. AI enrichment
          adds depth when a provider is configured.
Contact : rayyanxumair@gmail.com
GitHub  : github.com/rayyan-umair/LogClaw

"Technology evolves quickly. Responsibility does not."

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Part of the NetRaptor ecosystem.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

# ── Standard Library ──────────────────────────────────────────────────────────
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

log = logging.getLogger("logclaw.five_w")


# ── 5W+H Template Library ─────────────────────────────────────────────────────
# Hardcoded templates for every built-in alert type.
# Every student and analyst gets full investigative context
# even without an AI key configured.

TEMPLATES: Dict[str, Dict[str, Any]] = {

    "brute_force": {
        "what": (
            "Repeated authentication failures were detected against a single account. "
            "A brute force attack systematically tries many passwords until one works. "
            "This pattern indicates an automated attack tool is targeting this account."
        ),
        "why": (
            "The number of failed login attempts exceeded the detection threshold within "
            "the correlation window. This volume is statistically inconsistent with "
            "normal user behaviour and matches documented brute force attack patterns "
            "(MITRE ATT&CK T1110)."
        ),
        "investigation_commands": [
            "# Check all recent failed logins for this account (Windows):",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4625] and EventData[Data[@Name='TargetUserName']='{actor}']]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# Check if any succeeded after the failures:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4624] and EventData[Data[@Name='TargetUserName']='{actor}']]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# Check source IP geolocation - is it expected?",
            "# Use: https://ipinfo.io/{source_ip}",
            "",
            "# Linux - check auth.log for the same pattern:",
            "grep 'Failed password' /var/log/auth.log | grep '{actor}' | tail -50",
        ],
        "remediation_steps": [
            "1. Lock the targeted account immediately if the attack is ongoing.",
            "2. Force a password reset for the account.",
            "3. Block the source IP at the firewall if confirmed as malicious.",
            "4. Enable account lockout policy: lock after 5 failures for 30 minutes.",
            "5. Enable MFA on this account if not already active.",
            "6. Review all successful logins from the source IP across all accounts.",
        ],
    },

    "credential_stuffing": {
        "what": (
            "A successful authentication was recorded immediately following a series of "
            "failed attempts against the same account. This pattern is consistent with "
            "a successful brute force attack or credential stuffing - where a valid "
            "username and password combination was found."
        ),
        "why": (
            "The sequence of failures followed by a success from the same source matches "
            "the credential stuffing and brute force success pattern documented in "
            "MITRE ATT&CK T1110. This is a high-confidence indicator of account compromise."
        ),
        "investigation_commands": [
            "# Review all activity from this account after the successful login:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4624] and EventData[Data[@Name='TargetUserName']='{actor}']]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# Check for file access events after login:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=5140]]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# Check for new processes created after login:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4688] and EventData[Data[@Name='SubjectUserName']='{actor}']]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# Review account's group memberships:",
            "net user {actor} /domain",
        ],
        "remediation_steps": [
            "1. IMMEDIATELY force a password reset for the compromised account.",
            "2. Invalidate all active sessions for this account.",
            "3. Review all actions taken by this account since the successful login.",
            "4. Check for new services, scheduled tasks, or accounts created after the login.",
            "5. Block the source IP at the firewall.",
            "6. Enable MFA on this account.",
            "7. Determine how the password was obtained - check for credential dumps or phishing.",
        ],
    },

    "lateral_movement": {
        "what": (
            "The same account was used to authenticate to multiple distinct hosts within "
            "a short time window. Lateral movement is the technique attackers use to "
            "move through a network after gaining initial access - spreading from host "
            "to host to reach higher-value targets."
        ),
        "why": (
            "Authenticating to multiple hosts in rapid succession is not typical user "
            "behaviour. This pattern matches lateral movement techniques documented in "
            "MITRE ATT&CK T1021 (Remote Services). Combined with other indicators, "
            "this may represent an active intrusion in progress."
        ),
        "investigation_commands": [
            "# Map all hosts this account has touched recently:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4624] and EventData[Data[@Name='TargetUserName']='{actor}']]\" | Select-Object TimeCreated, @{N='Computer';E={$_.MachineName}} | Format-Table",
            "",
            "# Check for remote execution on each affected host:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4688] and EventData[Data[@Name='SubjectUserName']='{actor}']]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# List active sessions from domain controller:",
            "Get-NetSession -ComputerName {source_host}",
            "",
            "# Check for PSExec or WMI artifacts:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=7045]]\" | Where-Object {$_.Message -match 'PSEXESVC|WMI'} | Format-List",
        ],
        "remediation_steps": [
            "1. Disable the compromised account immediately.",
            "2. Isolate all hosts the account authenticated to from the network.",
            "3. Preserve memory dumps and disk images from affected hosts for forensic analysis.",
            "4. Identify the initial access vector - how was the account first compromised?",
            "5. Check all affected hosts for persistence mechanisms: services, scheduled tasks, registry run keys.",
            "6. Rotate credentials for all accounts that share passwords with the compromised account.",
            "7. Review domain controller logs for any domain-level changes.",
        ],
    },

    "privilege_escalation_chain": {
        "what": (
            "An account logged in and was subsequently added to a privileged security "
            "group within the same time window. This sequence suggests an attacker "
            "gained access and immediately escalated their privileges - a pattern "
            "seen in many documented breaches."
        ),
        "why": (
            "The combination of a new authentication event followed by a group "
            "membership change matches the privilege escalation chain documented "
            "in MITRE ATT&CK T1078 (Valid Accounts) and T1098 (Account Manipulation). "
            "Legitimate administrators rarely add accounts to privileged groups "
            "immediately after a fresh login without prior change approval."
        ),
        "investigation_commands": [
            "# Check which group was modified:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4728 or EventID=4732 or EventID=4756]]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# List current members of privileged groups:",
            "Get-ADGroupMember -Identity 'Domain Admins' | Select-Object Name, SamAccountName",
            "Get-ADGroupMember -Identity 'Administrators' | Select-Object Name, SamAccountName",
            "",
            "# Check who made the group change:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4728]]\" | Select-Object TimeCreated, @{N='SubjectUser';E={$_.Properties[4].Value}}, @{N='TargetUser';E={$_.Properties[0].Value}} | Format-Table",
            "",
            "# Review the login event that preceded this:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4624] and EventData[Data[@Name='SubjectUserName']='{actor}']]\" | Select-Object TimeCreated, Message | Format-List",
        ],
        "remediation_steps": [
            "1. Remove the account from the privileged group immediately.",
            "2. Disable the account that made the change if not a known administrator.",
            "3. Review all actions taken by the newly privileged account.",
            "4. Check for additional accounts added to privileged groups in the same window.",
            "5. Review domain controller audit logs for any other changes.",
            "6. Implement a change approval process for privileged group modifications.",
            "7. Enable alerts for all privileged group changes going forward.",
        ],
    },

    "persistence_after_auth": {
        "what": (
            "A new service or scheduled task was created on a host shortly after "
            "an authentication event. Persistence mechanisms allow attackers to "
            "maintain access to a system across reboots and session timeouts. "
            "This pattern is a strong indicator of an attacker establishing a foothold."
        ),
        "why": (
            "The temporal relationship between a login event and a persistence "
            "mechanism installation matches the persistence tactic documented in "
            "MITRE ATT&CK T1543 (Create or Modify System Process) and T1053 "
            "(Scheduled Task/Job). Legitimate software installation rarely follows "
            "immediately after an interactive login without a documented change."
        ),
        "investigation_commands": [
            "# Check the new service details:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=7045]]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# List all services created in the last 24 hours:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=7045 or EventID=4697]]\" | Where-Object {$_.TimeCreated -gt (Get-Date).AddHours(-24)} | Format-List",
            "",
            "# Check scheduled tasks:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4698]]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# List all current scheduled tasks:",
            "Get-ScheduledTask | Where-Object {$_.State -ne 'Disabled'} | Select-Object TaskName, TaskPath, State",
            "",
            "# Check the service binary path:",
            "Get-Service | Where-Object {$_.Status -eq 'Running'} | Select-Object Name, DisplayName",
            "sc.exe qc {service_name}",
        ],
        "remediation_steps": [
            "1. Stop and disable the suspicious service or scheduled task immediately.",
            "2. Identify and quarantine the binary associated with the persistence mechanism.",
            "3. Submit the binary to VirusTotal: https://www.virustotal.com",
            "4. Check if the same binary or task exists on other hosts in the network.",
            "5. Review all activity from the account that created the service.",
            "6. Check for additional persistence mechanisms: registry run keys, startup folders, WMI subscriptions.",
            "7. Preserve the binary and associated logs for forensic analysis before removal.",
        ],
    },

    "audit_log_cleared": {
        "what": (
            "The Windows Security audit log was cleared. This is one of the most "
            "significant indicators of a security incident. Attackers clear event "
            "logs to destroy evidence of their activities and make forensic "
            "investigation more difficult."
        ),
        "why": (
            "Log clearing matches MITRE ATT&CK T1070.001 (Indicator Removal: "
            "Clear Windows Event Logs). Legitimate administrators rarely clear "
            "the Security audit log. When they do, there is always a documented "
            "business reason. An unexplained log clear should be treated as a "
            "confirmed compromise indicator until proven otherwise."
        ),
        "investigation_commands": [
            "# Event 1102 confirms the log was cleared - check who did it:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=1102]]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# Check System log for related events around the same time:",
            "Get-WinEvent -LogName System | Where-Object {$_.TimeCreated -gt (Get-Date).AddHours(-1)} | Format-List",
            "",
            "# Check if other logs were also cleared:",
            "Get-WinEvent -ListLog * | Where-Object {$_.RecordCount -eq 0} | Select-Object LogName",
            "",
            "# Recover events from backup if available:",
            "# Check: C:\\Windows\\System32\\winevt\\Logs\\",
            "",
            "# Check for VSS shadow copies that may contain older logs:",
            "vssadmin list shadows",
        ],
        "remediation_steps": [
            "1. Treat this host as compromised until proven otherwise.",
            "2. Isolate the host from the network immediately to prevent further spread.",
            "3. Preserve the current state - memory dump and disk image - before any changes.",
            "4. Collect logs from other sources: network devices, domain controller, DHCP server.",
            "5. Review VSS shadow copies for older log data.",
            "6. Identify the account that cleared the logs and investigate all its recent activity.",
            "7. Check all other hosts for the same account's activity in the same timeframe.",
            "8. Implement a log forwarding solution so future logs are preserved off-host.",
        ],
    },

    "after_hours_auth": {
        "what": (
            "An authentication event was recorded outside of normal business hours. "
            "While legitimate, after-hours access by established accounts is worth "
            "investigating - particularly when combined with other indicators or "
            "when the account does not normally work outside business hours."
        ),
        "why": (
            "After-hours authentication deviates from the established baseline for "
            "this entity. This matches MITRE ATT&CK T1078 (Valid Accounts) where "
            "attackers use compromised credentials and often operate during off-hours "
            "to reduce the chance of detection by monitoring staff."
        ),
        "investigation_commands": [
            "# Check what the account did after logging in:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4688] and EventData[Data[@Name='SubjectUserName']='{actor}']]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# Check file access events:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=5140]]\" | Where-Object {$_.TimeCreated -gt (Get-Date).AddHours(-12)} | Format-List",
            "",
            "# Verify with the account owner - was this expected?",
            "# Contact {actor} directly to confirm the access was legitimate.",
            "",
            "# Check the source IP:",
            "# Is it the user's known IP or a new one?",
        ],
        "remediation_steps": [
            "1. Verify with the account owner that the access was legitimate.",
            "2. If unconfirmed, force a password reset and review all activity from the session.",
            "3. Enable MFA to prevent unauthorised after-hours access.",
            "4. Configure alerts for this account specifically for after-hours activity.",
            "5. If confirmed compromise, treat as a full incident and begin IR procedures.",
        ],
    },

    "new_source_auth": {
        "what": (
            "An account authenticated from a source host or IP address that has "
            "not been seen before in the monitoring window. This may indicate "
            "a new device, a VPN connection, or a compromised account being "
            "used from an attacker-controlled machine."
        ),
        "why": (
            "Authentication from a new source deviates from established baseline "
            "behaviour for this entity. Attackers using stolen credentials typically "
            "authenticate from infrastructure that differs from the victim's normal "
            "access patterns, matching MITRE ATT&CK T1078 (Valid Accounts)."
        ),
        "investigation_commands": [
            "# Check the source IP reputation:",
            "# https://ipinfo.io/{source_ip}",
            "# https://www.abuseipdb.com/check/{source_ip}",
            "",
            "# Verify the source host is a known asset:",
            "# Compare against your asset inventory",
            "",
            "# Check what the account did during this session:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4624] and EventData[Data[@Name='TargetUserName']='{actor}']]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# Confirm with the account owner:",
            "# Was {actor} working from a new location or device?",
        ],
        "remediation_steps": [
            "1. Verify with the account owner that the new source is expected.",
            "2. If the source is unknown, force a password reset immediately.",
            "3. Check the source IP against threat intelligence feeds.",
            "4. Review all actions taken during this session.",
            "5. Enable MFA to prevent future access from unknown sources.",
        ],
    },

    "stale_account_active": {
        "what": (
            "An account that has been inactive for an extended period suddenly "
            "became active. Stale accounts are a common attack vector - they often "
            "have old, weak passwords and are not monitored. Attackers deliberately "
            "target these accounts precisely because they attract less attention."
        ),
        "why": (
            "The account had no activity within the stale threshold period and then "
            "suddenly appeared in authentication events. This matches the Valid "
            "Accounts technique (MITRE ATT&CK T1078) where attackers exploit "
            "dormant accounts to blend in with legitimate activity."
        ),
        "investigation_commands": [
            "# Check when this account last authenticated before today:",
            "Get-ADUser {actor} -Properties LastLogonDate | Select-Object Name, LastLogonDate",
            "",
            "# Check account properties:",
            "Get-ADUser {actor} -Properties * | Select-Object Name, Enabled, PasswordLastSet, LastLogonDate, MemberOf",
            "",
            "# Review recent activity from this account:",
            "Get-WinEvent -FilterXPath \"*[EventData[Data[@Name='TargetUserName']='{actor}']]\" | Select-Object TimeCreated, Id, Message | Format-List",
            "",
            "# Check if password was changed recently:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4723 or EventID=4724] and EventData[Data[@Name='TargetUserName']='{actor}']]\" | Format-List",
        ],
        "remediation_steps": [
            "1. Verify with the account owner that the activity was legitimate.",
            "2. If unconfirmed, disable the account immediately.",
            "3. Force a password reset before re-enabling.",
            "4. Review all activity from this account during the active period.",
            "5. Implement a stale account review process - disable accounts after 90 days of inactivity.",
            "6. Remove stale accounts from all security groups.",
            "7. Run a full audit of all accounts inactive for 90+ days.",
        ],
    },

    "new_account_created": {
        "what": (
            "A new user account was created on this host or in the domain. "
            "Account creation is a common persistence technique - attackers "
            "create backdoor accounts to maintain access even after a "
            "password reset on the compromised account."
        ),
        "why": (
            "Unexpected account creation matches MITRE ATT&CK T1136 (Create Account). "
            "Legitimate account creation follows a documented process with an approval "
            "trail. An account created outside of normal provisioning procedures - "
            "especially outside business hours or by an unusual actor - should be "
            "treated as suspicious."
        ),
        "investigation_commands": [
            "# Get details of the newly created account:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4720]]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# Check who created the account:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4720]]\" | Select-Object @{N='Creator';E={$_.Properties[4].Value}}, @{N='NewAccount';E={$_.Properties[0].Value}}, TimeCreated | Format-Table",
            "",
            "# Check if the new account was immediately added to groups:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4728 or EventID=4732]]\" | Where-Object {$_.TimeCreated -gt (Get-Date).AddHours(-1)} | Format-List",
            "",
            "# Verify against your provisioning system - is this account expected?",
        ],
        "remediation_steps": [
            "1. Verify whether this account creation was authorised via your provisioning process.",
            "2. If unauthorised, disable the account immediately.",
            "3. Check if the account was added to any groups - remove if so.",
            "4. Identify the account that created it and review its recent activity.",
            "5. Check for other recently created accounts that may not have been detected.",
            "6. Implement alerting for all account creation events going forward.",
        ],
    },

    "group_membership_change": {
        "what": (
            "A user account was added to a security group. Adding an account to "
            "a privileged group - such as Domain Admins, Administrators, or Remote "
            "Desktop Users - immediately grants elevated access across the environment."
        ),
        "why": (
            "Unauthorised group membership changes match MITRE ATT&CK T1098 "
            "(Account Manipulation). Privilege escalation via group membership "
            "is a documented technique used in many high-profile breaches. "
            "All group changes should be verified against a change approval record."
        ),
        "investigation_commands": [
            "# Get details of the group change:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4728 or EventID=4732 or EventID=4756]]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# List current members of the affected group:",
            "Get-ADGroupMember -Identity '{target}' | Select-Object Name, SamAccountName, ObjectClass",
            "",
            "# Check who made the change:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4728]]\" | Select-Object @{N='ModifiedBy';E={$_.Properties[4].Value}}, @{N='MemberAdded';E={$_.Properties[0].Value}}, TimeCreated | Format-Table",
            "",
            "# Verify against change management records - was this approved?",
        ],
        "remediation_steps": [
            "1. Verify whether this group change was authorised.",
            "2. If unauthorised, remove the account from the group immediately.",
            "3. Review what actions the account took with its new privileges.",
            "4. Identify the account that made the change and review its activity.",
            "5. Implement a change approval workflow for all privileged group modifications.",
            "6. Enable real-time alerting for all Domain Admins group changes.",
        ],
    },

    "new_service": {
        "what": (
            "A new Windows service was installed on this host. Services run with "
            "elevated privileges and start automatically - making them ideal for "
            "persistence. Malware frequently installs itself as a service to survive "
            "reboots and run in the background without user interaction."
        ),
        "why": (
            "Service installation matches MITRE ATT&CK T1543.003 (Create or Modify "
            "System Process: Windows Service). Combined with other indicators, "
            "a new service should be investigated to confirm it is a legitimate "
            "application and not malware establishing persistence."
        ),
        "investigation_commands": [
            "# Get service details from the event:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=7045]]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# Find and inspect the service binary:",
            "Get-WmiObject Win32_Service | Where-Object {$_.Name -eq '{service_name}'} | Select-Object Name, PathName, StartMode, State",
            "",
            "# Calculate hash of the service binary:",
            "Get-FileHash 'C:\\path\\to\\service.exe' -Algorithm SHA256",
            "",
            "# Submit hash to VirusTotal:",
            "# https://www.virustotal.com/gui/file/{hash}",
            "",
            "# Check digital signature:",
            "Get-AuthenticodeSignature 'C:\\path\\to\\service.exe'",
            "",
            "# Check service account permissions:",
            "sc.exe qc {service_name}",
        ],
        "remediation_steps": [
            "1. Stop the service immediately if it cannot be verified as legitimate.",
            "2. Submit the service binary to VirusTotal before deleting it.",
            "3. Disable and delete the service if confirmed malicious.",
            "4. Search for the same binary hash on all other hosts in the environment.",
            "5. Check for related persistence mechanisms: scheduled tasks, registry run keys.",
            "6. Preserve a copy of the binary and associated event logs for forensic analysis.",
            "7. Identify the execution chain - how was the service installed?",
        ],
    },

    "scheduled_task_created": {
        "what": (
            "A new scheduled task was created. Scheduled tasks run automatically "
            "at specified times or events with the privileges of the creating account. "
            "They are one of the most common persistence mechanisms used by both "
            "malware and attackers operating manually."
        ),
        "why": (
            "Scheduled task creation matches MITRE ATT&CK T1053.005 (Scheduled "
            "Task/Job: Scheduled Task). Legitimate software creates scheduled tasks "
            "during installation - but tasks created interactively outside of "
            "software installation deserve investigation."
        ),
        "investigation_commands": [
            "# Get details of the new task:",
            "Get-WinEvent -FilterXPath \"*[System[EventID=4698]]\" | Select-Object TimeCreated, Message | Format-List",
            "",
            "# List all scheduled tasks and their actions:",
            "Get-ScheduledTask | Select-Object TaskName, TaskPath, @{N='Action';E={$_.Actions.Execute}} | Format-Table",
            "",
            "# Get details of a specific task:",
            "Get-ScheduledTaskInfo -TaskName '{task_name}'",
            "",
            "# Check the task's binary or script:",
            "# Identify the executable or script the task runs",
            "# Submit to VirusTotal if unknown",
            "",
            "# Check when the task was created:",
            "Get-ScheduledTask | Select-Object TaskName, @{N='Date';E={$_.Date}} | Sort-Object Date -Descending | Select-Object -First 20",
        ],
        "remediation_steps": [
            "1. Identify the task and verify it against known legitimate software.",
            "2. Disable the task immediately if it cannot be verified.",
            "3. Inspect the binary or script the task executes.",
            "4. Delete the task and its associated files if confirmed malicious.",
            "5. Search for the same task on other hosts in the environment.",
            "6. Identify the account that created the task and review its recent activity.",
        ],
    },

    # ── Default template for unknown alert types ───────────────────────────────
    "default": {
        "what": (
            "A security event was detected that matches a known suspicious pattern. "
            "Review the alert details and the associated events to determine "
            "the nature and scope of the activity."
        ),
        "why": (
            "This alert was generated because the detected activity matched a "
            "configured detection rule. The specific rule and its rationale are "
            "detailed in the alert metadata."
        ),
        "investigation_commands": [
            "# Review the triggering events in LogClaw",
            "# Check the entity timeline for the involved actor",
            "# Cross-reference with other alerts in the same time window",
            "# Verify the activity with the account owner if applicable",
        ],
        "remediation_steps": [
            "1. Review the full alert details and associated events.",
            "2. Determine whether the activity was authorised.",
            "3. If unauthorised, contain the affected account or host.",
            "4. Preserve evidence before making changes.",
            "5. Follow your organisation's incident response procedures.",
        ],
    },
}


# ── 5W+H Engine ───────────────────────────────────────────────────────────────

class FiveWEngine:
    """
    Transforms structured alert data into 5W+H investigative narratives.

    Every alert gets:
    - WHO:  The actor involved
    - WHAT: Plain-English description of what happened
    - WHERE: The affected host or network location
    - WHEN: Timestamp with relative context
    - WHY:  Why this was flagged - rule logic or anomaly reasoning
    - HOW:  Investigation commands + remediation steps

    Works entirely without AI. AI enrichment adds an additional
    narrative layer when configured.
    """

    async def generate(
        self,
        alert:         Dict[str, Any],
        trigger_event: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Generate a complete 5W+H object for an alert.
        Returns a dict with keys: who, what, where, when, why, how.
        """
        alert_type  = alert.get("alert_type", "default")
        actor       = alert.get("actor", "unknown")
        source_host = alert.get("source_host", "unknown")
        timestamp   = alert.get("timestamp", "")
        description = alert.get("description", "")
        metadata    = alert.get("metadata", {})

        # Get template - fall back to default for unknown types
        # Strip sigma: prefix for sigma alerts
        template_key = alert_type
        if alert_type.startswith("sigma:"):
            template_key = "default"
        template = TEMPLATES.get(template_key, TEMPLATES["default"])

        # ── WHO ───────────────────────────────────────────────────────────────
        who = self._build_who(actor, trigger_event, metadata)

        # ── WHAT ──────────────────────────────────────────────────────────────
        what = template.get("what", TEMPLATES["default"]["what"])

        # ── WHERE ─────────────────────────────────────────────────────────────
        where = self._build_where(source_host, trigger_event, metadata)

        # ── WHEN ──────────────────────────────────────────────────────────────
        when = self._build_when(timestamp, metadata)

        # ── WHY ───────────────────────────────────────────────────────────────
        why = self._build_why(template, alert, description, metadata)

        # ── HOW ───────────────────────────────────────────────────────────────
        how = self._build_how(template, actor, source_host, metadata)

        return {
            "who":   who,
            "what":  what,
            "where": where,
            "when":  when,
            "why":   why,
            "how":   how,
        }

    # ── Section Builders ──────────────────────────────────────────────────────

    def _build_who(
        self,
        actor:         str,
        trigger_event: Dict,
        metadata:      Dict,
    ) -> Dict[str, Any]:
        """Build the WHO section."""
        entity = trigger_event.get("entity", {})
        target = trigger_event.get("entity", {}).get("target") or trigger_event.get("target", "unknown")

        # Determine actor type
        actor_type = "unknown"
        if "@" in actor:
            parts = actor.split("@")
            actor_type = "user with source IP"
            actor_name = parts[0]
            source_ip  = parts[1] if len(parts) > 1 else "unknown"
        elif any(c.isdigit() for c in actor) and "." in actor:
            actor_type = "IP address"
            actor_name = actor
            source_ip  = actor
        elif actor.endswith("$"):
            actor_type = "computer account"
            actor_name = actor
            source_ip  = "unknown"
        else:
            actor_type = "user account"
            actor_name = actor
            source_ip  = "unknown"

        return {
            "actor":      actor,
            "actor_name": actor_name,
            "actor_type": actor_type,
            "target":     target,
            "summary":    f"{actor_type.title()}: {actor}",
        }

    def _build_where(
        self,
        source_host:   str,
        trigger_event: Dict,
        metadata:      Dict,
    ) -> Dict[str, Any]:
        """Build the WHERE section."""
        target = (
            trigger_event.get("entity", {}).get("target") or
            trigger_event.get("target") or
            "unknown"
        )

        affected_hosts = metadata.get("distinct_hosts", [source_host])
        if isinstance(affected_hosts, str):
            affected_hosts = [affected_hosts]

        return {
            "source_host":    source_host,
            "target":         target,
            "affected_hosts": affected_hosts,
            "host_count":     len(affected_hosts),
            "summary": (
                f"Host: {source_host}"
                if len(affected_hosts) <= 1
                else f"{len(affected_hosts)} hosts: {', '.join(affected_hosts[:3])}"
            ),
        }

    def _build_when(
        self,
        timestamp: str,
        metadata:  Dict,
    ) -> Dict[str, Any]:
        """Build the WHEN section with relative time context."""
        try:
            ts = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
        except (ValueError, AttributeError):
            ts = datetime.now(timezone.utc)

        now         = datetime.now(timezone.utc)
        delta       = now - ts
        total_secs  = int(delta.total_seconds())

        if total_secs < 60:
            relative = f"{total_secs} seconds ago"
        elif total_secs < 3600:
            relative = f"{total_secs // 60} minutes ago"
        elif total_secs < 86400:
            relative = f"{total_secs // 3600} hours ago"
        else:
            relative = f"{total_secs // 86400} days ago"

        span_seconds = metadata.get("span_seconds", 0)
        if span_seconds:
            if span_seconds < 60:
                span_str = f"{span_seconds}s"
            elif span_seconds < 3600:
                span_str = f"{span_seconds // 60}m {span_seconds % 60}s"
            else:
                span_str = f"{span_seconds // 3600}h {(span_seconds % 3600) // 60}m"
        else:
            span_str = None

        return {
            "timestamp":     ts.isoformat(),
            "relative":      relative,
            "utc_formatted": ts.strftime("%Y-%m-%d %H:%M:%S UTC"),
            "hour":          ts.hour,
            "is_after_hours": ts.hour >= 18 or ts.hour < 7,
            "attack_span":   span_str,
            "summary": (
                f"{ts.strftime('%H:%M:%S UTC')} ({relative})"
                + (f" - span: {span_str}" if span_str else "")
            ),
        }

    def _build_why(
        self,
        template:    Dict,
        alert:       Dict,
        description: str,
        metadata:    Dict,
    ) -> Dict[str, Any]:
        """Build the WHY section - detection rationale."""
        why_text = template.get("why", TEMPLATES["default"]["why"])

        # Add specific counts from metadata
        details = []
        if "failure_count" in metadata:
            details.append(f"Failure count: {metadata['failure_count']}")
        if "threshold" in metadata:
            details.append(f"Detection threshold: {metadata['threshold']}")
        if "host_count" in metadata:
            details.append(f"Hosts involved: {metadata['host_count']}")
        if "login_count" in metadata:
            details.append(f"Related logins: {metadata['login_count']}")

        mitre_tech = alert.get("mitre_technique", "")
        mitre_tact = alert.get("mitre_tactic", "")
        sigma_id   = alert.get("sigma_rule_id", "")

        return {
            "explanation":     why_text,
            "detection_detail": description,
            "specifics":       details,
            "mitre_technique": mitre_tech,
            "mitre_tactic":    mitre_tact,
            "sigma_rule_id":   sigma_id,
            "mitre_url": (
                f"https://attack.mitre.org/techniques/{mitre_tech.replace('.', '/')}/"
                if mitre_tech else None
            ),
            "summary": (
                f"Rule: {sigma_id}" if sigma_id
                else f"MITRE {mitre_tech}" if mitre_tech
                else "Correlation rule match"
            ),
        }

    def _build_how(
        self,
        template:    Dict,
        actor:       str,
        source_host: str,
        metadata:    Dict,
    ) -> Dict[str, Any]:
        """Build the HOW section - investigation commands and remediation."""
        raw_commands = template.get("investigation_commands", [])
        remediation  = template.get("remediation_steps", [])

        # Substitute placeholders in commands
        commands = []
        for cmd in raw_commands:
            cmd = cmd.replace("{actor}", actor)
            cmd = cmd.replace("{source_host}", source_host)
            cmd = cmd.replace("{source_ip}", actor.split("@")[-1] if "@" in actor else actor)
            # Replace other metadata placeholders
            for key, val in metadata.items():
                if isinstance(val, str):
                    cmd = cmd.replace(f"{{{key}}}", val)
            commands.append(cmd)

        # Separate commands by platform
        windows_commands = [c for c in commands if "Get-" in c or "sc.exe" in c or "net " in c.lower()]
        linux_commands   = [c for c in commands if "grep" in c or "/var/log" in c or "journalctl" in c]
        general_commands = [c for c in commands if c not in windows_commands and c not in linux_commands]

        return {
            "investigation_commands": commands,
            "windows_commands":       windows_commands,
            "linux_commands":         linux_commands,
            "general_commands":       general_commands,
            "remediation_steps":      remediation,
            "command_count":          len([c for c in commands if c.strip() and not c.startswith("#")]),
            "summary": (
                f"{len(remediation)} remediation steps  ·  "
                f"{len([c for c in commands if c.strip() and not c.startswith('#')])} commands"
            ),
        }

    # ── Batch Generation ──────────────────────────────────────────────────────

    async def generate_batch(
        self,
        alerts:        List[Dict],
        trigger_event: Dict,
    ) -> List[Dict]:
        """Generate 5W+H for a list of alerts."""
        results = []
        for alert in alerts:
            five_w = await self.generate(alert, trigger_event)
            results.append(five_w)
        return results

    # ── Template Management ───────────────────────────────────────────────────

    def get_available_templates(self) -> List[str]:
        """Return list of alert types with hardcoded templates."""
        return [k for k in TEMPLATES if k != "default"]

    def get_template(self, alert_type: str) -> Optional[Dict]:
        """Get the raw template for an alert type."""
        return TEMPLATES.get(alert_type)