"""
LogClaw Brain - Alerts API
alerts.py - Alert query, status management, and acknowledgement endpoints

Author  : Rayyan Umair
Date    : 2026-05-09
Purpose : REST endpoints for querying, filtering, acknowledging, and
          resolving alerts generated by the correlation engine and
          Sigma rule engine. Also provides alert statistics and
          the alert feed used by the frontend.
Contact : rayyanxumair@gmail.com
GitHub  : github.com/rayyan-umair/LogClaw

"Technology evolves quickly. Responsibility does not."
"""

# ── Standard Library ──────────────────────────────────────────────────────────
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List, Optional

# ── Third Party ───────────────────────────────────────────────────────────────
from fastapi import APIRouter, HTTPException, Query, Request
from pydantic import BaseModel

router = APIRouter()


# ── Request Models ────────────────────────────────────────────────────────────

class AlertStatusUpdate(BaseModel):
    status: str          # acknowledged | resolved | false_positive | open
    by:     Optional[str] = None  # analyst name or ID


class AlertNarrativeRequest(BaseModel):
    alert_id: str


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.get("/")
async def get_alerts(
    request:    Request,
    limit:      int   = Query(default=100, ge=1, le=1000),
    offset:     int   = Query(default=0,   ge=0),
    severity:   Optional[str] = Query(default=None, description="CRITICAL|HIGH|MEDIUM|LOW|INFO"),
    status:     Optional[str] = Query(default=None, description="open|acknowledged|resolved|false_positive"),
    actor:      Optional[str] = Query(default=None),
    alert_type: Optional[str] = Query(default=None),
    since:      Optional[str] = Query(default=None),
    open_only:  bool = Query(default=False),
) -> Dict[str, Any]:
    """
    Query alerts with optional filtering.
    Sorted by severity score descending then timestamp descending.
    """
    if open_only:
        status = "open"

    since_dt = None
    if since:
        try:
            since_dt = datetime.fromisoformat(since.replace("Z", "+00:00"))
        except ValueError:
            pass

    alerts, total = await request.app.state.storage.get_alerts(
        limit=limit,
        offset=offset,
        severity=severity,
        status=status,
        actor=actor,
        alert_type=alert_type,
        since=since_dt,
    )

    return {
        "alerts":   alerts,
        "total":    total,
        "limit":    limit,
        "offset":   offset,
        "has_more": (offset + limit) < total,
    }


@router.get("/feed")
async def get_alert_feed(
    request: Request,
    limit:   int = Query(default=50, ge=1, le=200),
    since:   Optional[str] = Query(default=None),
) -> Dict[str, Any]:
    """
    Get the live alert feed - open alerts ordered newest first.
    Used by the frontend alert panel.
    """
    since_dt = None
    if since:
        try:
            since_dt = datetime.fromisoformat(since.replace("Z", "+00:00"))
        except ValueError:
            since_dt = datetime.now(timezone.utc) - timedelta(hours=24)
    else:
        since_dt = datetime.now(timezone.utc) - timedelta(hours=24)

    alerts, total = await request.app.state.storage.get_alerts(
        limit=limit,
        status="open",
        since=since_dt,
    )

    return {
        "alerts":    alerts,
        "total":     total,
        "since":     since_dt.isoformat(),
        "unread":    total,
    }


@router.get("/stats")
async def get_alert_stats(request: Request) -> Dict[str, Any]:
    """Get alert statistics - counts by severity and type."""
    import asyncio
    loop   = asyncio.get_event_loop()
    storage = request.app.state.storage

    by_severity = await loop.run_in_executor(
        None,
        storage._fetchall,
        """
        SELECT severity, COUNT(*) as count
        FROM alerts
        GROUP BY severity
        ORDER BY count DESC
        """,
        (),
    )

    by_type = await loop.run_in_executor(
        None,
        storage._fetchall,
        """
        SELECT alert_type, COUNT(*) as count
        FROM alerts
        GROUP BY alert_type
        ORDER BY count DESC
        LIMIT 20
        """,
        (),
    )

    by_status = await loop.run_in_executor(
        None,
        storage._fetchall,
        """
        SELECT status, COUNT(*) as count
        FROM alerts
        GROUP BY status
        """,
        (),
    )

    last_24h = await loop.run_in_executor(
        None,
        storage._fetchall,
        """
        SELECT COUNT(*) FROM alerts
        WHERE timestamp >= now() - INTERVAL '24 hours'
        """,
        (),
    )

    corr_stats = await request.app.state.correlation.get_stats()

    return {
        "by_severity":    {str(r[0]): r[1] for r in by_severity},
        "by_type":        {str(r[0]): r[1] for r in by_type},
        "by_status":      {str(r[0]): r[1] for r in by_status},
        "last_24h":       last_24h[0][0] if last_24h else 0,
        "correlation":    corr_stats,
    }


@router.get("/{alert_id}")
async def get_alert(
    request:  Request,
    alert_id: str,
) -> Dict[str, Any]:
    """Get a single alert by ID with full 5W+H detail."""
    import asyncio
    loop = asyncio.get_event_loop()
    rows = await loop.run_in_executor(
        None,
        request.app.state.storage._fetchall,
        "SELECT * FROM alerts WHERE alert_id = ?",
        (alert_id,),
    )
    if not rows:
        raise HTTPException(
            status_code=404,
            detail=f"Alert {alert_id} not found",
        )
    return request.app.state.storage._row_to_alert(rows[0])


@router.patch("/{alert_id}/status")
async def update_alert_status(
    request:  Request,
    alert_id: str,
    body:     AlertStatusUpdate,
) -> Dict[str, Any]:
    """
    Update alert status - acknowledge, resolve, or mark as false positive.
    Valid status values: open | acknowledged | resolved | false_positive
    """
    valid_statuses = {"open", "acknowledged", "resolved", "false_positive"}
    if body.status not in valid_statuses:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid status. Must be one of: {valid_statuses}",
        )

    success = await request.app.state.storage.update_alert_status(
        alert_id=alert_id,
        status=body.status,
        by=body.by,
    )

    if not success:
        raise HTTPException(
            status_code=404,
            detail=f"Alert {alert_id} not found",
        )

    return {
        "alert_id": alert_id,
        "status":   body.status,
        "updated":  True,
    }


@router.post("/{alert_id}/narrative")
async def generate_ai_narrative(
    request:  Request,
    alert_id: str,
) -> Dict[str, Any]:
    """
    Generate or regenerate the AI narrative for an alert.
    Requires AI to be configured in settings.
    """
    settings = request.app.state.settings
    if not settings.is_ai_configured:
        raise HTTPException(
            status_code=400,
            detail="AI is not configured. Set AI_ENABLED=true and configure a provider.",
        )

    # Get the alert
    import asyncio
    loop = asyncio.get_event_loop()
    rows = await loop.run_in_executor(
        None,
        request.app.state.storage._fetchall,
        "SELECT * FROM alerts WHERE alert_id = ?",
        (alert_id,),
    )
    if not rows:
        raise HTTPException(status_code=404, detail=f"Alert {alert_id} not found")

    alert = request.app.state.storage._row_to_alert(rows[0])

    # Generate narrative via AI
    try:
        from ai.client import AIClient
        client    = AIClient(settings.ai_provider, settings.ai_api_key)
        narrative = await asyncio.get_event_loop().run_in_executor(
            None,
            lambda: client.generate_alert_narrative(alert),
        )
        await request.app.state.storage.update_alert_ai_narrative(
            alert_id=alert_id,
            narrative=narrative,
        )
        return {
            "alert_id":  alert_id,
            "narrative": narrative,
            "generated": True,
        }
    except Exception as ex:
        raise HTTPException(
            status_code=500,
            detail=f"AI narrative generation failed: {ex}",
        )


@router.get("/{alert_id}/five-w")
async def get_alert_five_w(
    request:  Request,
    alert_id: str,
) -> Dict[str, Any]:
    """Get the 5W+H investigative breakdown for an alert."""
    import asyncio
    loop = asyncio.get_event_loop()
    rows = await loop.run_in_executor(
        None,
        request.app.state.storage._fetchall,
        "SELECT five_w, alert_id, title, severity FROM alerts WHERE alert_id = ?",
        (alert_id,),
    )
    if not rows:
        raise HTTPException(status_code=404, detail=f"Alert {alert_id} not found")

    import json
    five_w_raw = rows[0][0]
    five_w     = json.loads(five_w_raw) if five_w_raw else {}

    return {
        "alert_id": alert_id,
        "title":    rows[0][2],
        "severity": rows[0][3],
        "five_w":   five_w,
    }