/*
LogClaw Harvester — Log Ingestion Agent
main.go — Entry point, lifecycle management, ZeroMQ publisher

Author  : Rayyan Umair
Date    : 2026-05-09
Purpose : Orchestrates all log collectors. Normalises raw logs into
          the universal LogClaw schema and streams them to the
          Intelligence Brain via ZeroMQ PUB socket.
Contact : rayyanxumair@gmail.com
GitHub  : github.com/rayyan-umair/LogClaw

"Technology evolves quickly. Responsibility does not."

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Part of the NetRaptor ecosystem.
  This binary handles ingestion ONLY. No analysis. No storage.
  No correlation. All intelligence lives in the Python brain.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
*/

package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"

	zmq4 "github.com/go-zeromq/zmq4"
)

// ── Version ───────────────────────────────────────────────────────────────────

const (
	Version    = "1.0.0"
	AppName    = "LogClaw Harvester"
	AppAuthor  = "Rayyan Umair"
	AppTagline = "Technology evolves quickly. Responsibility does not."
)

// ── Universal Log Schema ──────────────────────────────────────────────────────
// Every log source normalises into this structure before transmission.
// The Brain receives only this — never raw log formats.

type LogEvent struct {
	EventID   string `json:"event_id"`  // UUID generated by harvester
	Timestamp string `json:"timestamp"` // UTC ISO8601 — always UTC, always
	Platform  string `json:"platform"`  // windows | linux | network | file
	Source    string `json:"source"`    // hostname or device identifier

	Entity struct {
		Actor  string `json:"actor"`  // user / service / IP performing the action
		Target string `json:"target"` // host / service / endpoint being acted upon
	} `json:"entity"`

	Event struct {
		Type        string `json:"type"`         // auth | network | config | process | file | system
		Severity    int    `json:"severity"`     // 0–10
		RawEventID  int    `json:"raw_event_id"` // Windows Event ID or syslog facility
		Description string `json:"description"`  // normalised human-readable description
	} `json:"event"`

	MITRE struct {
		TechniqueID string `json:"technique_id"` // T1110, T1078, etc. — empty if unknown
		TacticName  string `json:"tactic_name"`  // credential-access, lateral-movement, etc.
	} `json:"mitre"`

	RawPayload string `json:"raw_payload"` // original log line — preserved for reference
}

// ── Config ────────────────────────────────────────────────────────────────────

type Config struct {
	// ZeroMQ
	ZMQAddress string // where to publish — brain subscribes here

	// WinRM targets
	WinRMHosts    []string
	WinRMUser     string
	WinRMPassword string
	WinRMPort     int

	// SSH / Linux targets
	SSHHosts    []string
	SSHUser     string
	SSHKeyPath  string
	SSHLogPaths []string // e.g. /var/log/auth.log, /var/log/syslog

	// Syslog UDP listener
	SyslogPort int

	// EVTX fallthrough — for systems where WinRM is disabled
	EVTXPaths []string

	// Polling intervals
	WinRMInterval time.Duration
	SSHInterval   time.Duration
	SyslogEnabled bool
}

func defaultConfig() *Config {
	return &Config{
		ZMQAddress:    "tcp://127.0.0.1:5555",
		WinRMPort:     5985,
		WinRMInterval: 10 * time.Second,
		SSHInterval:   10 * time.Second,
		SyslogPort:    514,
		SyslogEnabled: true,
		SSHLogPaths: []string{
			"/var/log/auth.log",
			"/var/log/syslog",
			"/var/log/secure",
			"/var/log/kern.log",
			"/var/log/audit/audit.log",
		},
	}
}

// ── Publisher ─────────────────────────────────────────────────────────────────

type Publisher struct {
	socket  zmq4.Socket
	mu      sync.Mutex
	sent    int64
	dropped int64
}

func NewPublisher(address string) (*Publisher, error) {
	sock := zmq4.NewPub(context.Background())
	if err := sock.Listen(address); err != nil {
		return nil, fmt.Errorf("zmq bind %s: %w", address, err)
	}
	log.Printf("[ZMQ] Publisher bound on %s", address)
	return &Publisher{socket: sock}, nil
}

func (p *Publisher) Publish(event *LogEvent) error {
	data, err := json.Marshal(event)
	if err != nil {
		return fmt.Errorf("marshal event: %w", err)
	}
	p.mu.Lock()
	defer p.mu.Unlock()
	msg := zmq4.NewMsgFrom([]byte("log:"), data)
	if err := p.socket.Send(msg); err != nil {
		p.dropped++
		return fmt.Errorf("zmq send: %w", err)
	}
	p.sent++
	return nil
}

func (p *Publisher) Stats() (sent, dropped int64) {
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.sent, p.dropped
}

func (p *Publisher) Close() {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.socket.Close()
}

// ── Collector Interface ───────────────────────────────────────────────────────
// Every log source implements this. The orchestrator runs all of them
// concurrently and they all publish to the same ZeroMQ socket.

type Collector interface {
	Name() string
	Start(ctx context.Context, pub *Publisher) error
}

// ── Orchestrator ──────────────────────────────────────────────────────────────

type Orchestrator struct {
	cfg        *Config
	pub        *Publisher
	collectors []Collector
	wg         sync.WaitGroup
}

func NewOrchestrator(cfg *Config, pub *Publisher) *Orchestrator {
	return &Orchestrator{cfg: cfg, pub: pub}
}

func (o *Orchestrator) Register(c Collector) {
	o.collectors = append(o.collectors, c)
}

func (o *Orchestrator) Run(ctx context.Context) {
	log.Printf("[%s] v%s — starting %d collector(s)", AppName, Version, len(o.collectors))

	for _, c := range o.collectors {
		o.wg.Add(1)
		go func(col Collector) {
			defer o.wg.Done()
			log.Printf("[%s] starting", col.Name())
			if err := col.Start(ctx, o.pub); err != nil {
				// Collectors should handle their own retries.
				// A fatal error here means the collector gave up entirely.
				log.Printf("[%s] stopped: %v", col.Name(), err)
			}
		}(c)
	}
}

func (o *Orchestrator) Wait() {
	o.wg.Wait()
}

// ── Stats Reporter ────────────────────────────────────────────────────────────
// Logs throughput every 60 seconds so you can see the harvester is alive.

func startStatsReporter(ctx context.Context, pub *Publisher) {
	go func() {
		ticker := time.NewTicker(60 * time.Second)
		defer ticker.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				sent, dropped := pub.Stats()
				log.Printf("[STATS] sent=%d dropped=%d", sent, dropped)
			}
		}
	}()
}

// ── Main ──────────────────────────────────────────────────────────────────────

func main() {
	// ── Flags ────────────────────────────────────────────────────────────────
	zmqAddr := flag.String("zmq", "tcp://127.0.0.1:5555", "ZeroMQ publish address")
	winrmHosts := flag.String("winrm", "", "Comma-separated WinRM hosts")
	winrmUser := flag.String("winrm-user", "", "WinRM username")
	winrmPass := flag.String("winrm-pass", "", "WinRM password")
	sshHosts := flag.String("ssh", "", "Comma-separated SSH hosts")
	sshUser := flag.String("ssh-user", "", "SSH username")
	sshKey := flag.String("ssh-key", "", "Path to SSH private key")
	syslogPort := flag.Int("syslog-port", 514, "UDP syslog listener port")
	evtxPaths := flag.String("evtx", "", "Comma-separated .evtx file paths")
	noSyslog := flag.Bool("no-syslog", false, "Disable syslog listener")
	flag.Parse()

	// ── Banner ────────────────────────────────────────────────────────────────
	fmt.Printf("\n  ◈ %s  v%s\n", AppName, Version)
	fmt.Printf("  %s\n", AppTagline)
	fmt.Printf("  github.com/rayyan-umair/LogClaw\n\n")

	// ── Config ────────────────────────────────────────────────────────────────
	cfg := defaultConfig()
	cfg.ZMQAddress = *zmqAddr
	cfg.WinRMUser = *winrmUser
	cfg.WinRMPassword = *winrmPass
	cfg.SSHUser = *sshUser
	cfg.SSHKeyPath = *sshKey
	cfg.SyslogPort = *syslogPort
	cfg.SyslogEnabled = !*noSyslog

	if *winrmHosts != "" {
		cfg.WinRMHosts = splitHosts(*winrmHosts)
	}
	if *sshHosts != "" {
		cfg.SSHHosts = splitHosts(*sshHosts)
	}
	if *evtxPaths != "" {
		cfg.EVTXPaths = splitHosts(*evtxPaths)
	}

	// ── ZeroMQ Publisher ──────────────────────────────────────────────────────
	pub, err := NewPublisher(cfg.ZMQAddress)
	if err != nil {
		log.Fatalf("[FATAL] ZeroMQ publisher: %v", err)
	}
	defer pub.Close()

	// ── Signal Handling ───────────────────────────────────────────────────────
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		sig := <-sigCh
		log.Printf("[SIGNAL] received %s — shutting down gracefully", sig)
		cancel()
	}()

	// ── Orchestrator ──────────────────────────────────────────────────────────
	orch := NewOrchestrator(cfg, pub)

	// Register collectors based on config
	if len(cfg.WinRMHosts) > 0 {
		orch.Register(NewWinRMCollector(cfg))
	}
	if len(cfg.SSHHosts) > 0 {
		orch.Register(NewSSHCollector(cfg))
	}
	if cfg.SyslogEnabled {
		orch.Register(NewSyslogCollector(cfg))
	}
	if len(cfg.EVTXPaths) > 0 {
		orch.Register(NewEVTXCollector(cfg))
	}

	if len(orch.collectors) == 0 {
		log.Println("[WARN] No collectors configured.")
		log.Println("       Use --winrm, --ssh, --evtx flags or enable --syslog-port")
		log.Println("       Run with --help to see all options.")
		os.Exit(1)
	}

	// ── Start ─────────────────────────────────────────────────────────────────
	startStatsReporter(ctx, pub)
	orch.Run(ctx)
	orch.Wait()

	sent, dropped := pub.Stats()
	log.Printf("[DONE] total sent=%d dropped=%d", sent, dropped)
}

// ── Helpers ───────────────────────────────────────────────────────────────────

func splitHosts(s string) []string {
	var hosts []string
	for _, h := range splitString(s, ',') {
		if h != "" {
			hosts = append(hosts, h)
		}
	}
	return hosts
}

func splitString(s string, sep rune) []string {
	var parts []string
	start := 0
	for i, r := range s {
		if r == sep {
			parts = append(parts, s[start:i])
			start = i + 1
		}
	}
	parts = append(parts, s[start:])
	return parts
}
